# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8070
  servlet:
    context-path: /rabbitmq

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
    virtual-host: /testmq #相当于一个虚拟空间
    listener:
      simple:
        concurrency: 3 #消费者最小数量
        max-concurrency: 10 # 消费者最大数量